apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  label: 
    app: tomcat
    env: dev
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        env: dev
    spec:
      containers:
        - name: tomcat-container
          image: {{ .Values.spec.image.repository }}:{{ .Values.spec.image.tag }}
          imagePullPolicy: {{ .Values.spec.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.spec.resources | nindent 12 }}
