apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    env: prod
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: tomcat-deployment
  targetCPUUtilizationPercentage: 90