apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: tomcat
  type: ClusterIP
